### PR TITLE
add limits to gas fee, fix en-GB message, fix issue in edge

### PR DESCRIPTION
**Pull request by hendoban**

### CODE REVIEW

**Review by AlexSSD7 — CHANGES_REQUESTED** [review]
What's the purpose of the limit? Can you please just fix it so it will work with any gas price limits?

The effective limit here is `2^64`, aka `uint64`.

**Comment by indyramp** [comment]
@AlexSSD7  The observed issue with the gas price limit being too high is that the user was unable to change it back after it was set obscenely high. I don't know what the back-end cause of this was, but I could imagine it happening again if someone set an obscenely high value again.

**Review by AlexSSD7 — COMMENTED** [review]
Doesn't seem that the `%action` issue was resolved in Dutch.

image

This will likely require a translation update from Crowdin, which I will do in the next PR.

**Comment by AlexSSD7** [comment]
> @AlexSSD7 The observed issue with the gas price limit being too high is that the user was unable to change it back after it was set obscenely high. I don't know what the back-end cause of this was, but I could imagine it happening again if someone set an obscenely high value again.

It is an issue with the frontend, not with the backend.

**Pull request closed without merging**
