### PR TITLE
Fix approximate block share, add payout limit warnings

### PR DESCRIPTION
**Pull request by march08**

### CODE REVIEW

**Review by AlexSSD7 — CHANGES_REQUESTED** [review]
Text here should be white regardless of the theme. Also, the coloring for the light theme is not the best.
image

Spelling: change zil to ZIL please.
image

And also the share log size in the FAQ should be changed from 6M to 1M.

P.S. For some reason on Ubuntu, the default theme points to Light theme even though the system theme is set to Dark.

**Comment by march08** [comment]
@AlexSSD7 are you using chrome? https://askubuntu.com/questions/1321701/detecting-dark-mode-on-web-apps

**Comment by march08** [comment]
Screen Shot 2021-05-13 at 15 20 01
colors, the yellow is a bit darker to make the white mor ereadable

**Comment by AlexSSD7** [comment]
> @AlexSSD7 are you using chrome? https://askubuntu.com/questions/1321701/detecting-dark-mode-on-web-apps

yes

**Review by AlexSSD7 — APPROVED** [review]
LGTM

**Pull request merged**
