### PR TITLE
Redirect old miner address URL, handle error when address is not found

### LINKED ISSUE #52: Miner link backwards compatibility with old website
TL;DR

```
/0x918d65E6B3820f82fE2013eFb9596C9876312F72
```
Should point to
```
/miner/eth/0x918d65E6B3820f82fE2013eFb9596C9876312F72
```

### PR DESCRIPTION
**Pull request by march08**
resolve #52

### CODE REVIEW

**Comment by AlexSSD7** [comment]
This works with every combination of text even if it is not an address.

image

**Review by AlexSSD7 — CHANGES_REQUESTED** [review]
Please, verify the address via the standard Ethereum address regex: `^0x[a-fA-F0-9]{40}$`

**Comment by AlexSSD7** [comment]
Also, please take a look at #63

**Comment by march08** [comment]
adding 404, resolves #64

Now page `/miner/:coin/:address` does a validation first against `/miner/locateAddress` api endpoint, validating an address against our database. This way we handle the miner page properly when not found for all cases (not only eth regex)

if address exists, page will render the miner page as usually
If address doesn't exist, page will redirect to `/not-found`

**Review by AlexSSD7 — APPROVED** [review]
LGTM

**Pull request merged**
