### PR TITLE
UX Worker search bar, Miner Search bar UI, Miner dashboard nav

### PR DESCRIPTION
**Pull request by march08**
Worker search bar hover ui, clear icon
For some reason i can't run the old beta version anymore

### CODE REVIEW

**Review by AlexSSD7 — CHANGES_REQUESTED** [review]
~~The underline is too slow and doesn't look smooth.~~ (Only applies to miners with a high worker count.)

Also, I think [X] buttons should be done in the same way as they are done in the v1 website modal.

**Comment by march08** [comment]
Modal [x]

Screen Shot 2021-05-03 at 16 42 01
Screen Shot 2021-05-03 at 16 42 05

search x

Screen Shot 2021-05-03 at 16 42 44
Screen Shot 2021-05-03 at 16 42 46

**Review by AlexSSD7 — CHANGES_REQUESTED** [review]
Can you please make it more rounded?

**Comment by march08** [comment]
Screen Shot 2021-05-04 at 9 54 18
@AlexSSD7

**Review by AlexSSD7 — CHANGES_REQUESTED** [review]
Can you please do the same for all X buttons?

**Comment by march08** [comment]
Screen Shot 2021-05-05 at 12 27 35
Any other occurances @AlexSSD7 ?
Also changed the hover state

**Comment by march08** [comment]
Screen Shot 2021-05-05 at 12 30 22
Miner nav bar

**Comment by AlexSSD7** [comment]
> Miner nav bar

@march08 Can't see it. Perhaps forgot to push?

**Comment by march08** [comment]
@AlexSSD7 ah yes, true, pushing now

**Comment by march08** [comment]
@AlexSSD7 updated

**Review by AlexSSD7 — APPROVED** [review]
LGTM

**Pull request merged**
