### PR TITLE
UX Searchbar - search limit to 6, add to redux, removable address

### PR DESCRIPTION
**Pull request by march08**

### CODE REVIEW

**Review by AlexSSD7 — CHANGES_REQUESTED** [review]
Can't see a remove button?
image
Also, I don't think that "hover to open the menu" is a great UX solution. Probably, it is better to remove it. (a lot of false positives when you just pass the cursor over)

**Review by AlexSSD7 — CHANGES_REQUESTED** [review]
The autocomplete menu becomes hidden when the (x) button is clicked.

**Comment by march08** [comment]
@AlexSSD7 should be good now

**Review by AlexSSD7 — APPROVED** [review]
LGTM

**Pull request merged**
