### PR TITLE
UX Tables, header navigation hover

### PR DESCRIPTION
**Pull request by march08**
persistent hover, click

### CODE REVIEW

**Comment by AlexSSD7** [comment]
Warnings should be removed

**Comment by AlexSSD7** [comment]
Please remove table hover animations. They make the UI look very slow.

**Comment by AlexSSD7** [comment]
Hover here should also underline the wallet address so the user will understand what he is clicking.
image

**Comment by march08** [comment]
@AlexSSD7 ok you can check now

**Comment by march08** [comment]
added header navigation hover changes

**Comment by AlexSSD7** [comment]
For blocks table, I don't think that you need to apply the all-cell clickable table row feature.

**Comment by march08** [comment]
@AlexSSD7 the idea here is to keep the UX consistent across the website. You can still click on the block number etc. Thoughts?

**Comment by AlexSSD7** [comment]
Block number will work I think. Also, I think that the link should not be underlined when the table row is not hovered.

**Comment by march08** [comment]
@AlexSSD7 up

**Comment by AlexSSD7** [comment]
LGTM on tables (well done, they feel really good). On the nav hover, there is too much empty space. Also, the hover on the logo is not implemented.

**Review by AlexSSD7 — APPROVED** [review]
LGTM

**Pull request merged**
