### PR TITLE
remove start url so browser picks it instead

### PR DESCRIPTION
**Pull request by march08**
maybe this will help, cannot test localy

### CODE REVIEW

**Comment by AlexSSD7** [comment]
What is the purpose of this PR?

**Comment by march08** [comment]
@AlexSSD7 
Screen Shot 2021-04-13 at 16 54 15

**Comment by march08** [comment]
site.webmanifest is not being used so that has been removed

**Review by AlexSSD7 — APPROVED** [review]
Alright, that will need to be changed to `https://flexpool.io` on the final release.

**Pull request merged**
