### PR TITLE
Minor theme change to miner distribution chart and reworded blocks counter sentence

### PR DESCRIPTION
**Pull request by HippityHoppityXD**
Cosmetic change with miner distribution chart and reworded blocks counter sentence for main blocks page and single blocks in miner dashboard.

### Main blocks page
**Current**
> You have mined 3355 block(s).

**Changed**
> Flexpool has mined 3355 blocks.

### MMiner dashboard blocks page
**Current**
> You have mined 1 block(s).

> You have mined 2 block(s).

**Changed**
> You have mined a block.

> You have mined 2 blocks.

### Cosmetic change to miner distribution chart (light mode)
Possibly change the outline of the pie chart dependent on theme to match the text color, eg using ('#111432') for light mode, and keeping ('#fff') for dark mode.

**Current**
image

**Changed**
image

### CODE REVIEW

**Comment by march08** [comment]
Personally I am not sure if I even like the dark border around the chart
The wording on the blocks section on the other hand is great, do you think you can split the PR into two? @HippityHoppityXD

**Comment by march08** [comment]
Also instead of "a block" if you can change it to "1 block"

**Comment by HippityHoppityXD** [comment]
I'll open another PR with just the block sentence changes.

**Comment by march08** [comment]
@HippityHoppityXD also please feel free to open a second one to keep it active

**Pull request closed without merging**
