### PR TITLE
Nicehash guide, 14444 port details

### PR DESCRIPTION
**Pull request by march08**

### CODE REVIEW

**Comment by march08** [comment]
@AlexSSD7 
Screen Shot 2021-05-13 at 16 38 05
Screen Shot 2021-05-13 at 16 38 00

**Comment by march08** [comment]
@AlexSSD7 i'll be adding secondary selection next pr

**Comment by AlexSSD7** [comment]
@march08 Only high difficulty port works with nicehash. Remove all other regions, please.

**Review by AlexSSD7 — CHANGES_REQUESTED** [review]
Only high difficulty port works with nicehash. Remove all other regions, please.

**Review by AlexSSD7 — APPROVED** [review]
LGTM

**Review by AlexSSD7 — CHANGES_REQUESTED** [review]
It is better to have a separate row for Nicehash.

**Comment by march08** [comment]
@AlexSSD7 what do you mean by separate row? Where?

**Pull request merged**
