### PR TITLE
Fix glitchy dropdown select

### LINKED ISSUE #406: Glitchy Select components across application
Kapture 2021-08-25 at 22 42 15
Kapture 2021-08-25 at 22 42 25

### PR DESCRIPTION
**Pull request by aminick**
This PR fixes #406, provides WAI-ARIA compliant dropdown select, that is super responsive, and keyboard friendly.

Kapture 2021-09-03 at 09 26 40

Keyboard support:
Kapture 2021-09-03 at 09 29 35

### CODE REVIEW

**Comment by aminick** [comment]
After some period of time on production, I will slowly clean up all legacy implementations.

**Comment by aminick** [comment]
This PR is also a good foundation for #326

**Review by AlexSSD7 — CHANGES_REQUESTED** [review]
image

The text is dark here for some reason sometimes.

image

Also, that black border doesn't look very nice.

FYI using Chrome

**Review by AlexSSD7 — APPROVED** [review]
LGTM

**Pull request merged**
