### PR TITLE
Add auto update toggle

### PR DESCRIPTION
**Pull request by hendoban**
image

### CODE REVIEW

**Review by AlexSSD7 — COMMENTED** [review]
Fix warnings please, so I will be able to review

**Review by AlexSSD7 — CHANGES_REQUESTED** [review]
<div class="js-discussion js-socket-channel ml-0 pl-0 ml-md-6 pl-md-3" data-channel="eyJjIjoibWFya2VkLWFzLXJlYWQ6NDMwNDMzNDQiLCJ0IjoxNjIyMTMyOTQ3fQ==--a4bdfe7fc2d470c8b729d0882cb4515855f0970ef4471c2e764155cf50b2e939" data-channel-target="MDExOlB1bGxSZXF1ZXN0NjU1MTQwMTY1" style="box-sizing: border-box; margin-left: 40px !important; padding-left: 16px !important; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="js-timeline-item js-timeline-progressive-focus-container" data-gid="MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NjcwMzk5MTY4" style="box-sizing: border-box;"><div class="
            
            
            is-writer" style="box-sizing: border-box;"><div id="pullrequestreview-670399168" class="js-comment js-updatable-content js-socket-channel js-targetable-element" data-gid="MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NjcwMzk5MTY4" data-channel="eyJjIjoicHVsbF9yZXF1ZXN0X3Jldmlldzo2NzAzOTkxNjgiLCJ0IjoxNjIyMTMyOTQ3fQ==--9d6a690cae952db415d8ae8c6dcc73e79c7996dcd5f64708b4810ee769664489" data-url="/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NjcwMzk5MTY4/pull_request_reviews/body?variables%5BdeferredCommentActions%5D=false" style="box-sizing: border-box;"><div class="TimelineItem pt-0" style="box-sizing: border-box; padding: 16px 0px; position: relative; display: flex; margin-left: 16px;"><div class=" timeline-comment-group js-minimizable-comment-group js-targetable-element TimelineItem-body my-0 " id="pullrequestreview-670399168-body-html" style="box-sizing: border-box; margin-top: 4px; margin-bottom: 0px !important; min-width: 0px; max-width: 100%; color: var(--color-timeline-text); flex: 1 1 auto;"><div class="ml-n3 timeline-comment unminimized-comment comment previewable-edit js-task-list-container editable-comment js-comment timeline-comment--caret timeline-comment--caret-nw reorderable-task-lists current-user" data-body-version="486115e400bf10eb2d80896f3e52c277c62fe622541376a4b13b0464926f584b" data-unfurl-hide-url="/content_reference_attachments/hide" style="box-sizing: border-box; margin-left: -16px !important; position: relative; color: var(--color-text-primary); background-color: var(--color-bg-primary); border-color: var(--color-auto-blue-4); border-top-style: ; border-top-width: ; border-right-style: ; border-right-width: ; border-bottom-style: ; border-bottom-width: ; border-left-style: ; border-left-width: ; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-radius: 6px; box-shadow: 0 0 0 0.2em var(--color-auto-blue-2);"><div class="edit-comment-hide" style="box-sizing: border-box;"><task-lists sortable="" style="box-sizing: border-box;">Fix warnings please, so I will be able to review</task-lists></div><form class="js-comment-update" id="pullrequestreview-670399168-body-html-edit-form" action="https://github.com/flexpool/frontend/pull/236/reviews/670399168/update" accept-charset="UTF-8" method="post" style="box-sizing: border-box;"></form></div></div></div></div></div></div><div id="partial-timeline" class="js-timeline-marker js-socket-channel js-updatable-content" data-channel="eyJjIjoicHVsbF9yZXF1ZXN0OjY1NTE0MDE2NSIsInQiOjE2MjIxMzI5NDd9--cb9f748f1cb7f896045422b596e8b6a37ef88051fbf148992b218c557dcc763e" data-url="/_render_node/MDExOlB1bGxSZXF1ZXN0NjU1MTQwMTY1/pull_requests/unread_timeline?variables%5BdeferCommitBadges%5D=false&amp;variables%5BdeferStatusCheckRollups%5D=false&amp;variables%5BdeferredCommentActions%5D=true&amp;variables%5BhasFocusedReviewComment%5D=false&amp;variables%5BhasFocusedReviewThread%5D=false&amp;variables%5BtimelinePageSize%5D=30&amp;variables%5BtimelineSince%5D=2021-05-27T16%3A29%3A06Z" data-last-modified="Thu, 27 May 2021 16:29:06 GMT" data-gid="MDExOlB1bGxSZXF1ZXN0NjU1MTQwMTY1" style="box-sizing: border-box;"></div></div><div class="discussion-timeline-actions" style="box-sizing: border-box; background-color: var(--color-bg-canvas); border-top: 2px solid var(--color-border-primary); color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div id="partial-pull-merging" class="pull-merging js-pull-merging js-socket-channel js-updatable-content js-pull-refresh-on-pjax " aria-live="polite" data-channel="eyJjIjoicmVwbzozNTA0MDY1OTA6YnJhbmNoOnRhc2svaXNzdWUtMjI1L2F1dG9tYXRpYy1kYXRhLXJlZnJlc2giLCJ0IjoxNjIyMTMyOTQ4fQ==--a2f78868e004527b1a9f2d88724b564cb25a3799137bdfbde4ba6d5515ca1821 eyJjIjoicmVwbzozNTA0MDY1OTA6YnJhbmNoOmRldiIsInQiOjE2MjIxMzI5NDh9--58e060ab033357db1c5d4956fed58ab768db72e98b8d3e72680eac9100ff9b99 eyJjIjoicmVwbzozNTA0MDY1OTA6Y29tbWl0OmU2ZDBlYjQwYTU1ZWQwMmUxZGRjZDg5MzQ2ZTQyMDM3OTFiOGNlY2QiLCJ0IjoxNjIyMTMyOTQ4fQ==--db1c1f73d58eb605f984f3bc217e9868ed1e2d0d1feaf46e0b3dcfc0595be428 eyJjIjoiaXNzdWU6OTAzOTM1NDgwOnN0YXRlIiwidCI6MTYyMjEzMjk0OH0=--9521f240af9836147aa69cf2dd0cb15f63d05c33f87d5c7e8c572faaabda37c1 eyJjIjoicHVsbF9yZXF1ZXN0OjY1NTE0MDE2NTpyZXZpZXdfc3RhdGUiLCJ0IjoxNjIyMTMyOTQ4fQ==--bf6b8724d095ac7c061b40873ef694db2aea30f1b198ff935119032b47f825fc eyJjIjoicHVsbF9yZXF1ZXN0OjY1NTE0MDE2NTp3b3JrZmxvd19ydW4iLCJ0IjoxNjIyMTMyOTQ4fQ==--408feee3901bd0eaf3d519e7de3bf401c31fd4890032c098f507d64e604c44d4" data-url="/flexpool/frontend/pull/236/show_partial?merge_type=merge&amp;partial=pull_requests%2Fmerging" style="box-sizing: border-box;"><br class="Apple-interchange-newline"></div></div>

**Review by AlexSSD7 — CHANGES_REQUESTED** [review]
Misaligment here:

image

Also, the gray color here should not be that dark here. The button border may be too thick and/or the button being too small here, though I'm not sure:

image


Also, I feel that the reload button should not be removed. It is quite useful sometimes.

**Comment by hendoban** [comment]
Adjusted alignment, Moved refresh button to be next to settings for a more uniform look (button next to button)

**Review by AlexSSD7 — CHANGES_REQUESTED** [review]
Please use `--text-secondary` for the button & text when the auto-refresh is not active.

Also, please extend the clickable space so the user can use the text & toggle as one large button. (like it is done with nav items)

image

**Review by AlexSSD7 — CHANGES_REQUESTED** [review]
image

Doesn't correctly work on light mode. Also, no hover shadow on the button.

**Review by AlexSSD7 — CHANGES_REQUESTED** [review]
image

The paddings on the left are missing. Also, I feel that the animation is unnecessary here.

**Review by AlexSSD7 — CHANGES_REQUESTED** [review]
Something is wrong with the countdown after a couple of turn on & offs.

**Review by AlexSSD7 — CHANGES_REQUESTED** [review]
That loading on the auto-update toggle hurts the UX so much.

Also, I'd keep the previous refresh button styling here.

image

**Review by AlexSSD7 — APPROVED** [review]
LGTM

**Pull request merged**
