### PR TITLE
Add coin switcher to FAQ

### LINKED ISSUE #396: Add coin switcher to FAQ page
Ref: https://github.com/flexpool/frontend/issues/243#issuecomment-894123505

### PR DESCRIPTION
**Pull request by aminick**
This pr fixes #396

Test cases:
Frequently_Asked_Questions___Flexpool_io
Frequently_Asked_Questions___Flexpool_io-2

### CODE REVIEW

**Review by AlexSSD7 — CHANGES_REQUESTED** [review]
> How is payout criteria calculated?

Chia version should be a bit edited since there is no gas price there.

> My reported hashrate is unstable, will this effect my payouts?
> Why is my effective hashrate not stable?

Chia version should have `reported space` instead of `reported hashrate`

> Why is my effective hashrate not stable?

`AEH` there should be replaced with `Average Effective Hashrate` because it may be unclear for many people.

> How is share count calculated?

Chia version should have "points" instead of "shares"

> I am no longer mining, what do I do with my remaining balance?

Chia version should have "farming" instead of "mining"

> Mining Basics section

Better to remove it completely in Chia, and replace with a Chia-specific section in the future.

> What is Flexpool's pool fee?

It is better to centralize %'s, so it will be easier to apply pool fee changes.

> Should I use SSL?

Chia is always using SSL, so it is better to hide it.

... Regarding additional Chia-related FAQs, I ask @indyramp for help.

**Comment by indyramp** [comment]
Hi there. Here are my Chia FAQs - feel free to use any or all. 

https://www.reddit.com/r/Flexpool/comments/ombfmv/some_quick_frequently_asked_questions_about/

If you'd like I can rewrite in versicle-and-response format for the website FAQ - as my doc is more "answers to frequently asked questions" rather than the actual questions. :)

**Comment by aminick** [comment]
> Hi there. Here are my Chia FAQs - feel free to use any or all.
> 
> https://www.reddit.com/r/Flexpool/comments/ombfmv/some_quick_frequently_asked_questions_about/
> 
> If you'd like I can rewrite in versicle-and-response format for the website FAQ - as my doc is more "answers to frequently asked questions" rather than the actual questions. :)

That would be great indyramp. I am sure the you as the original author can come up with better questions than me. Thanks again.

**Comment by indyramp** [comment]
How to join Flexpool Chia pool?

With your Chia Network software, join the pool using one of our pool addresses on Getting Started. Within about an hour (100-110 blocks) your join will be complete. You must use a PlotNFT and plots made with a PlotNFT pool contract address; OG plots (made before Chia 1.2.0) or solo plots (not made with a PlotNFT) cannot be used for the pool.

What software do I need?

You need the Chia Blockchain software from Chia Network. You can find the latest version on https://chia.net/  . You should always run the latest version, and check for updates regularly. 

You may want to use third party software like the Madmax plotter (sponsored by Flexpool) or Bladebit plotter, or plot managers like Plotman and Swar. These are optional, but many Chia farmers find them useful. Please note that we do not provide official support for these software programs, but there are lots ofusers in our Telegram and Discord who may be able to help you out with them. Again, you should always run the latest version, and check for updates regularly. 

You may also wish to check out Flexpool's optional, proprietary, optimized farmer software called FlexFarmer. See our Getting Started page or our Reddit post for more details. Not surprisingly, you should always run the latest version, and check for updates regularly. 

Do I have to make new plots for Flexpool or FlexFarmer? 

If you are already pooling with an Official Protocol pool, you can use the same plots. Just use the Chia GUI to change pools, or the Chia CLI to leave the old pool and join Flexpool. 

The official pooling protocol does not support OG plots (those made before Chia 1.2.0, with an -f plotter option rather than -c), so you cannot use OG plots with our pool or any Official Protocol pool. You may still farm them solo with the Chia software while farming new plots to Flexpool. 

Our Getting Started page includes instructions for creating plots that work with pools. 

What is Flexpool's Chia pool fee?

Our Chia pool has a 0% fee at this time. It may change in the future, and we will announce any changes when they are decided. 

What is the minimum payout amount?

You may set your minimum payout to as low as 0.01 XCH, or as high as 10 XCH. The default is 0.1 XCH.

When do payouts happen? 

Payouts are hourly, and the results will appear on the Payments tab of your dashboard. Payouts are not at a specific minute of the hour, so you will usually not get paid out immediately when you reach your limit.

How many Chia do I get for X TB of plots?

There is an estimator on the front page of flexpool.io, and estimates are shown on your dashboard. These are estimates, not guarantees, and may change dramatically as pool luck and acreage change over time. Use them as a rule of thumb, not a commitment from the pool or the Chia blockchain. 

How are rewards calculated? What if I find a block?

We use the PPLNS (Pay Per Last N Shares) method, which takes your share of the most recent work submitted to the pool to determine your reward when the pool earns a reward. The current value of "N" is shown under "Share Log Wipeout Duration" on the dashboard under Reward, and at the time of this FAQ it is 500k shares. 

So if you have submitted 5k of the last 500k shares when a block is found, you would get 1%, or .0175 XCH, as your reward.

The farmer who "finds" a block for the pool is rewarded with 0.25 XCH "Farmer Reward" directly from the blockchain. This goes to your wallet automatically. The pool never touches that reward. 

What address do I use on the Flexpool website to see my dashboard?

You would use the payout address shown for your PlotNFT in the Chia software, or the payout address you configured in FlexFarmer if you are using it. We do *not* use the Launcher ID on our dashboard. 

Why doesn't my dashboard show up yet? I get the 404 Moon page.

Our dashboards activate within 20 minutes of your first valid partial being submitted to the pool. For farmers with 150 or more plots, this should mean your dashboard shows up and your worker is consistently active on it within 20 minutes. For farmers with fewer plots, it will take longer, and you may appear offline. With one plot, you might wait 6 hours and you might only appear online 10 times a day. 

Why do I have a lot of stale partials on the dashboard?

This is almost always a farmer-side issue, and is often caused by a flaky network (wifi with high interference, for example), heavy load on the farmer (from plotting or moving plots around),  or sometimes a suboptimal connection between you and the pool. Unlike ETH, Chia is not as susceptible to latency to the pool server, so while you can change servers to try to work around this, it's usually not an Internet path issue. Even 400ms latency to the pool server is usually acceptable. 

Why doesn't the pool show the exact space I have on my farm?

The Chia Network software, as of version 1.2.3 at least, does not report space to the pool. Therefore, we do not see your actual pooled space. The pool sees your number of partials submitted, and based on the Chia pooling guide's estimate of 10 points per plot per day, we estimate your space (and your share of the work, thus your share of the rewards) on your 24 hour point/partial count divided by 10. 

Example: If you have 10 points per day for your farm, that is normal for having one plot on the pool, so we estimate 0.1 TB. If you have 15000 points per day, that is normal for having 1500 plots, so we estimate about 150 TB. 

If you use FlexFarmer software, it *does* report your actual plot space, so Reported will have an accurate value. Your effective space is still calculated based on your points/partials though, so if you had 150TB reported but only submitted 5000 partials in 24 hours, we would estimate you at 500 plots or 50TB. As with Ethereum pools, you are paid based on your share of the work, not your amount of equipment, although normally they will be similar. 

It's been an hour and my unpaid balance hasn't changed?

Our pool only pays rewards when we earn rewards. If there are no blocks found for a period of time, there is no reward to share with farmers, so your rewards do not increase. 

You can check the Blocks tab at the top of any of our pages to see when the last block was found. If there is a spinning wheel next to the block number, it is not yet confirmed and may not be finalized yet. Sometimes blocks may take an hour to confirm and have a final reward value on your Rewards tab. 

I'm having problems with my farm. How can I get help?

Chia is a more complicated platform to troubleshoot. We recommend checking the Chia troubleshooting guide on our subreddit. Once you have checked those possible issues, you may either join our Telegram or Discord servers and get help from the community and the pool team, visit r/Flexpool or r/chia on Reddit, or find the "Help" or "Chat" button at the bottom right of any page on our website to get 1:1 support from our support team. 

Is your live support 24/7?

Not yet, although we have farmers around the world who may be able to help you on Discord or Telegram at any time. 

Our support team is online throughout the day though, so even if you see "Help" instead of "Chat" you can submit a request and will get an answer usually within several hours at most--sometimes within several minutes. Be sure to ask your question and include your payout address and any error messages you're getting. If you leave a message with  just "Hi" we can't start helping you when our team is online.

**Comment by indyramp** [comment]
@aminick I've got a transformed version... need to figure out how to upload it with the links intact. Stand by.

**Comment by indyramp** [comment]
[FAQ for chia website.html.pdf](https://github.com/flexpool/frontend/files/7028076/FAQ.for.chia.website.html.pdf)

Let me know if this is usable. Github won't let me upload a HTML file.

**Comment by aminick** [comment]
@indyramp Transferred to the website. Thanks for your work.

**Comment by indyramp** [comment]
Feedback so far from the mods:

"How to join Flexpool Chia pool" has the wrong link. It should link to https://www.flexpool.io/get-started

"What software do I need" - minor item, space missing in "lots ofusers" in second graf. 

And an item from me, to add to the Chia side. 

**"Why does my GUI show Current Difficulty of 1 and Current Points Balance of 9999?"**

'These are both normal for our pool. 

'Because of the way points and partials are handled on the back end, we use a static difficulty of 1. This enables more consistent estimated statistics, and does not adversely affect farmers' hard drives. 

'The points balance isn't used on our pool, so if you see 9999, that just says you have reached our pool successfully. The "Points Found in Last 24 Hours" number should equate to the numbers on our dashboard, and the "Points Successful in Last 24 Hours" number should be pretty close to the percentage of "Valid" points on the website.

**Review by AlexSSD7 — APPROVED** [review]
LGTM

**Pull request merged**
