### PR TITLE
Latest open report preview

### PR DESCRIPTION
**Pull request by march08**
Fe will try to guess the latest open report
renders the latest open report as a preview
renders list of all reports

### CODE REVIEW

**Comment by AlexSSD7** [comment]
After enabling CORS, I see that it is working. I will convert it to open PR.

**Comment by AlexSSD7** [comment]
One thing I think is required to be done is normal page switch animation.

**Comment by march08** [comment]
> One thing I think is required to be done is normal page switch animation.

I've added that, you should be able to check the deployment now

**Review by AlexSSD7 — APPROVED** [review]
LGTM

**Comment by AlexSSD7** [comment]
@march08 Please resolve the conflict.

**Pull request merged**
